apiVersion: apps/v1
kind: Deployment
metadata:
  name: actuator-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: actuator-pod
  template:
    metadata:
      labels:
        pod: actuator-pod
    spec:
      containers:
        - name: actuator-container
          image: ker10epere/spring-actuator:0.0.1
          env:
            - name: server.servlet.context-path
              value: /spring-actuator
            - name: server.port
              value: "8080"
            - name: logging.level.org.springframework.web.servlet.DispatcherServlet
              value: TRACE
