apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /test/$2
spec:
  rules:
    - http:
        paths:
          # ANOTHER PathType FOR PathPrefix TO REMOVE REGEX WARNINGS
          - pathType: ImplementationSpecific
            path: /demo(/|$)(.*)
            backend:
              service:
                # TARGETS THE SERVICE BY METADATA NAME
                name: webserver-svc
                port:
                  number: 8080
